{{- if .Values.server.setDatasource.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "server.fullname" . }}-set-datasource
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "wait-for-grafana",
            "image": "{{ .Values.server.setDatasource.initImage }}",
            "command": ["sh", "-c", "until curl --fail http://{{ .Values.server.adminUser }}:{{ .Values.server.adminPassword }}@{{ template "fullname" . }}:{{ .Values.server.httpPort }}/api/org; do echo waiting for myservice; sleep 5; done;"]
        }
    ]'
spec:
  restartPolicy: OnFailure
  containers:
  - name: {{ template "server.fullname" . }}-set-datasource
    image: "{{ .Values.server.setDatasource.image }}"
    args:
    - "http://{{ .Values.server.adminUser }}:{{ .Values.server.adminPassword }}@{{ template "fullname" . }}:{{ .Values.server.httpPort }}/api/datasources"
    - "-X"
    - POST
    - "-H"
    - "Content-Type: application/json;charset=UTF-8"
    - "--data-binary"
    {{- with .Values.server.setDatasource.datasource }}
    - |
      {"name":"{{ .name }}",
        "type":"{{ .type }}",
        "url":"{{ .url }}",
        "access":"{{ .access }}",
        "isDefault":{{ .isDefault }},
        {{- if contains "influxdb" .type }}
        "password":"{{ .influxdb.password }}",
        "user":"{{ .influxdb.user }}",
        "database":"{{ .influxdb.database }}"
        {{- end }}
        }
      {{- end }}
  {{- end -}}
