apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "server.fullname" . }}-import-dash-pods
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "wait-for-db",
            "image": "{{ .Values.server.setDatasource.initImage }}",
            "command": ["sh", "-c", "until curl --fail http://{{ .Values.server.adminUser }}:{{ .Values.server.adminPassword }}@{{ template "fullname" . }}:{{ .Values.server.httpPort }}/api/datasources/name/snap; do echo waiting for myservice; sleep 5; done;"]
        }
    ]'
spec:
  restartPolicy: OnFailure
  containers:
  - name: {{ template "server.fullname" . }}-import-dash-pods
    image: "{{ .Values.server.setDatasource.image }}"
    args:
    - "http://{{ .Values.server.adminUser }}:{{ .Values.server.adminPassword }}@{{ template "fullname" . }}:{{ .Values.server.httpPort }}/api/dashboards/db"
    - "-X"
    - POST
    - "-H"
    - "Content-Type: application/json;charset=UTF-8"
    - "--data-binary"
    - |
{{ tuple "dashboards/_pods.json.tpl" . | include "template" | indent 6 }}

