apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "fullname" . }}-config 
data: 
  snapteld.conf: |
{{ tuple "config/_snapteld.tpl" . | include "template" | indent 4 }}
  task.json: |
{{ tuple "config/_task.tpl" . | include "template" | indent 4 }}

