apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config 
  namespace: {{ .Release.Namespace }}
data: 
  snapteld.conf: |
{{ tuple "config/_snapteld.tpl" . | include "template" | indent 4 }}
  plugins.yaml: |
{{ tuple "config/_plugins.tpl" . | include "template" | indent 4 -}} 
