## Snap image version
## ref: https://hub.docker.com/r/intelsdi/snap4kube/tags/
namespace: kube-system
image:
  repo: intelsdi/snap4kube 
  tag: latest
  pullPolicy: IfNotPresent
mounts:
  "/proc": "/proc_host"
host_plugins: /opt/plugins
privileged: false
config:
  log_level: 1
  log_path: /snap
  autodiscover_path: /opt/snap/autoload 

