---
  version: 1
  name: docker
  schedule:
    type: "simple"
    interval: "30s"
    deadline: "30s"
  max-failures: -1
  workflow:
    collect:
      metrics:
        /intel/docker/*/stats/cgroups/cpu_stats/cpu_usage/per_cpu/*/value: {}
        /intel/docker/*/stats/cgroups/memory_stats/usage/usage: {}
        /intel/docker/*/stats/filesystem/*/usage: {}
        /intel/docker/*/stats/filesystem/*/available: {}
      config:
        /intel/docker:
          procfs: "/proc_host"
      tags:
        /intel/docker:
          nodename:
      publish:
      - plugin_name: "influxdb"
        config:
          host: "monitoring-influxdb"
          port: 8086
          database: "snap"
          user: admin 
          password: admin
          scheme: http
          skip-verify: true
          isMultiFields: false 

