{{- if .Values.setDefaultUser.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "fullname" . }}-create-user-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  activeDeadlineSeconds: {{ default 300 .Values.setDefaultUser.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-create-user
        image: {{ .Values.setDefaultUser.image | quote }}
        env:
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-auth
                key: influxdb-user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-auth
                key: influxdb-password
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -X POST http://monitoring-influxdb:8086/query \
             --data-urlencode \
             "q=CREATE USER \"${INFLUXDB_USER}\" WITH PASSWORD '${INFLUXDB_PASSWORD}' {{ .Values.setDefaultUser.user.privileges }}"
      restartPolicy: {{ .Values.setDefaultUser.restartPolicy }}
{{- end -}}
