apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  labels:
    app: {{ template "influxdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: api
    port: {{ .Values.port_number }}
    targetPort: {{ .Values.port_number }}
  selector:
    app: {{ template "influxdb.fullname" . }}
