apiVersion: v1
kind: Service
metadata:
  labels:
    daemon: snapteld
  name: snap-seed
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - port: 6000
    protocol: TCP
    name: tribe
  - port: 8181
    name: api
  selector:
    daemon: snapteld
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: snap
  namespace: kube-system
spec:
  serviceName: snap-seed
  # number of Snap tribe members
  replicas: 3
  template:
    metadata:
      labels:
        daemon: snapteld
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": [
                {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "daemon",
                        "operator": "In",
                        "values": [
                          "snapteld"
                        ]
                      }
                    ]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }
              ]
            }
          }
    spec:
      containers:
      - name: snap
        image: intelsdi/snap4kube:tribe
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - /tribe.sh
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /probe.sh
        ports:
        - containerPort: 6000
          name: seed
        - containerPort: 6001
          name: tribe
        - containerPort: 8182
          name: api
        - containerPort: 8181
          name: snap-api
        env:
          - name: SEED
            value: "snap-0.snap-seed.default.svc.cluster.local"
          - name: INITIAL_MEMBER 
            value: "snap-0"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: LOG_LEVEL
            value: "1"
        volumeMounts:
          - mountPath: /proc_host
            name: proc
      volumes:
        - name: proc
          hostPath:
            path: /proc
